### ISSUE TITLE
Зачем фиксировать .idea и все вложенные папки и файлы?

### ISSUE THREAD

**Issue by Raleose** [lex019020/CorpMessengerBackend#1]
Например, .vs/ или .git/ мы же не фиксируем

**Comment by lex019020** [comment]
Изначально я использовал VS, затем перешёл на Rider, и забыл дополнить .gitignore файл)

**Comment by lex019020** [comment]
Исправлено в коммите [98cad6](https://github.com/lex019020/CorpMessengerBackend/commit/d28cf55c0d4fe7e03052db5639862ec91098cad6)
