### ISSUE TITLE
Почему не используется валидация?

### ISSUE THREAD

**Issue by Raleose** [lex019020/CorpMessengerBackend#2]
В контрллерах захардкожена проверка if'ами, причем местами можно и ее упростить (`credentials.Token is "" or null` -> `string.IsNullOrEmpty(credentials.Token)`). Есть всякие nuget'ы с валидацией (FluentValidation, например).

**Comment by lex019020** [comment]
Некрасиво, согласен

**Comment by lex019020** [comment]
В принципе в контроллерах теперь только проверки флагов авторизации из отдельного сервиса, ну и валидации с запросами
