### ISSUE TITLE
Token можно хранить в header'ах

### ISSUE THREAD

**Issue by Raleose** [lex019020/CorpMessengerBackend#3]
Зачем в модель `Credentials` пихать Token? В ASP.NET используется конвеерный метод обработки запросов. Ты можешь сделать свою проверку токена и внедрить ее в конвеер, тогда нужные тебе запросы будут проверять наличие токена, его валидность, а твой код будет заниматься проверкой введенных данных из модели.

**Comment by lex019020** [comment]
Тут согласен, хороший повод разобраться в мидлварях всяких и конвеерной обработке. Буду фиксить.

**Comment by lex019020** [comment]
Проверку авторизации засунул в мидлварь, добавил сервис поставщика авторизации (возвращает флаг авторизации и userId) для упрощения интерфейса, если авторизация не успешна - запрос разворачивается мидлварем (за исключением запросов на аутентификацию))

[коммит 1](https://github.com/lex019020/CorpMessengerBackend/commit/04aec301848704088d25d26122ce042bdd4e86c6)
[коммит 2](https://github.com/lex019020/CorpMessengerBackend/commit/26ac4242001c0d541c9a1871034a65921b0b558e)
